-- Flux — Supabase Schema
-- Setup: SQL-Editor im Supabase Dashboard öffnen und diese Datei komplett ausführen.
-- Danach unter Authentication → Providers → Google aktivieren.

-- =========================================================
-- 1. PROFILES (1:1 mit auth.users)
-- =========================================================
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  theme text default 'system' check (theme in ('light', 'dark', 'system')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Trigger: legt automatisch einen Profile-Eintrag an, sobald sich
-- ein User neu registriert (Google OAuth, Email, …)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- =========================================================
-- 2. ARBEITS-DATEN — alle mit owner_id = auth.uid()
-- =========================================================
create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  detail text not null default '',
  amount text not null default '',
  time text not null default '',
  created_at timestamptz default now()
);
create index if not exists purchases_owner_idx on public.purchases(owner_id);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  detail text not null default '',
  amount text not null default '',
  time text not null default '',
  created_at timestamptz default now()
);
create index if not exists sales_owner_idx on public.sales(owner_id);

create table if not exists public.purchase_lines (
  id bigint primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  label text not null default '',
  amount numeric not null default 0,
  sort_order int not null default 0
);
create index if not exists purchase_lines_owner_idx on public.purchase_lines(owner_id);

create table if not exists public.shipping_lines (
  id bigint primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  label text not null default '',
  amount numeric not null default 0,
  sort_order int not null default 0
);
create index if not exists shipping_lines_owner_idx on public.shipping_lines(owner_id);

create table if not exists public.revenue_lines (
  id bigint primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  store text not null default '',
  amount numeric not null default 0,
  sort_order int not null default 0
);
create index if not exists revenue_lines_owner_idx on public.revenue_lines(owner_id);

create table if not exists public.purchase_batches (
  id bigint primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  label text not null default '',
  purchase_ids bigint[] not null default '{}',
  revenue_ids bigint[] not null default '{}',
  sort_order int not null default 0
);
create index if not exists purchase_batches_owner_idx on public.purchase_batches(owner_id);

create table if not exists public.delivery_rows (
  id bigint primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  box text not null default '',
  qr_data_url text,
  qr_name text,
  qr_kind text check (qr_kind in ('image', 'pdf')),
  invoice_data_url text,
  invoice_name text,
  invoice_kind text check (invoice_kind in ('image', 'pdf')),
  sort_order int not null default 0
);
create index if not exists delivery_rows_owner_idx on public.delivery_rows(owner_id);

-- =========================================================
-- 3. ROW LEVEL SECURITY — Nutzer sehen nur eigene Daten
-- =========================================================
alter table public.profiles       enable row level security;
alter table public.purchases      enable row level security;
alter table public.sales          enable row level security;
alter table public.purchase_lines enable row level security;
alter table public.shipping_lines enable row level security;
alter table public.revenue_lines  enable row level security;
alter table public.purchase_batches enable row level security;
alter table public.delivery_rows  enable row level security;

drop policy if exists "profiles_self"       on public.profiles;
drop policy if exists "purchases_self"      on public.purchases;
drop policy if exists "sales_self"          on public.sales;
drop policy if exists "purchase_lines_self" on public.purchase_lines;
drop policy if exists "shipping_lines_self" on public.shipping_lines;
drop policy if exists "revenue_lines_self"  on public.revenue_lines;
drop policy if exists "purchase_batches_self" on public.purchase_batches;
drop policy if exists "delivery_rows_self"  on public.delivery_rows;

create policy "profiles_self"       on public.profiles       using (id = auth.uid()) with check (id = auth.uid());
create policy "purchases_self"      on public.purchases      using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "sales_self"          on public.sales          using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "purchase_lines_self" on public.purchase_lines using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "shipping_lines_self" on public.shipping_lines using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "revenue_lines_self"  on public.revenue_lines  using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "purchase_batches_self" on public.purchase_batches using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "delivery_rows_self"  on public.delivery_rows  using (owner_id = auth.uid()) with check (owner_id = auth.uid());

-- =========================================================
-- 4. STORAGE — Bucket für Profilbilder (öffentlich lesbar)
-- =========================================================
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

drop policy if exists "avatar_public_read"   on storage.objects;
drop policy if exists "avatar_owner_upload"  on storage.objects;
drop policy if exists "avatar_owner_update"  on storage.objects;
drop policy if exists "avatar_owner_delete"  on storage.objects;

create policy "avatar_public_read"
  on storage.objects for select
  using (bucket_id = 'avatars');

create policy "avatar_owner_upload"
  on storage.objects for insert
  with check (bucket_id = 'avatars' and auth.uid() = owner);

create policy "avatar_owner_update"
  on storage.objects for update
  using (bucket_id = 'avatars' and auth.uid() = owner);

create policy "avatar_owner_delete"
  on storage.objects for delete
  using (bucket_id = 'avatars' and auth.uid() = owner);
