-- Flux — Supabase Schema v2
-- Erweitert: purchase_items, bilder, unique IDs, KI-Metadaten, profit-tracking
-- Setup: SQL-Editor im Supabase Dashboard öffnen und diese Datei komplett ausführen.
-- Danach unter Authentication → Providers → Google aktivieren.

-- =========================================================
-- 1. PROFILES
-- =========================================================
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  theme text default 'system' check (theme in ('light', 'dark', 'system')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- =========================================================
-- 2. PURCHASE ITEMS — die atomare Einheit (Schallplatte etc.)
-- =========================================================
create table if not exists public.purchase_items (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  purchase_id bigint,  -- null bis das Item einem Ankauf zugeordnet wird

  -- Eindeutige Lesbare ID (z.B. "A-00001")
  unique_code text not null default '',
  title text not null default '',
  description text not null default '',
  condition_notes text not null default '',

  -- Preis & Versand
  price_paid numeric(10,2) not null default 0,
  shipping_share numeric(10,2) not null default 0,  -- anteiliger Versand

  -- Zustand / Status
  status text not null default 'in_stock'
    check (status in ('in_stock', 'listed', 'reserved', 'sold')),

  -- Bild
  image_url text,
  extra_images text[] not null default '{}',

  -- KI-Generierung
  ai_title text,
  ai_description text,
  ai_generated_at timestamptz,

  -- Sale-Verknüpfung
  sold_at timestamptz,
  sale_price numeric(10,2),
  sale_order_id bigint,

  -- Timestamps
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists purchase_items_owner_idx on public.purchase_items(owner_id);
create index if not exists purchase_items_purchase_idx on public.purchase_items(purchase_id) where purchase_id is not null;
create index if not exists purchase_items_status_idx on public.purchase_items(status);
create unique index if not exists purchase_items_unique_code_idx on public.purchase_items(owner_id, unique_code) where unique_code != '';

-- =========================================================
-- 3. PURCHASES — der Haupt-Ankauf (Lieferant, Gesamtpreis)
-- =========================================================
create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,

  supplier_name text not null default '',
  description text not null default '',

  total_price numeric(10,2) not null default 0,
  shipping_price numeric(10,2) not null default 0,

  status text not null default 'active'
    check (status in ('draft', 'active', 'sold', 'archived')),

  -- Item-Counter für unique IDs
  item_counter int not null default 0,

  -- Timestamps
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists purchases_owner_idx on public.purchases(owner_id);

-- =========================================================
-- 4. PURCHASE IMAGES — Zusatz-Bilder pro Ankauf
-- =========================================================
create table if not exists public.purchase_images (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  purchase_id bigint not null references public.purchases(id) on delete cascade,
  image_url text not null,
  caption text not null default '',
  sort_order int not null default 0,
  created_at timestamptz default now()
);
create index if not exists purchase_images_purchase_idx on public.purchase_images(purchase_id);

-- =========================================================
-- 5. SALES (legacy - für Kompatibilität, Item-basiert erweitert)
-- =========================================================
create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,

  customer_name text not null default '',
  description text not null default '',
  amount text not null default '',
  time text not null default '',

  -- Erweitert für Item-Tracking
  status text not null default 'open'
    check (status in ('open', 'paid', 'shipped', 'completed')),

  created_at timestamptz default now()
);
create index if not exists sales_owner_idx on public.sales(owner_id);

-- =========================================================
-- 6. LEGACY TABELLEN — werden beibehalten für Rücksicht
-- =========================================================
create table if not exists public.purchase_lines (
  id bigint primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  label text not null default '',
  amount numeric not null default 0,
  sort_order int not null default 0
);
create index if not exists purchase_lines_owner_idx on public.purchase_lines(owner_id);

create table if not exists public.shipping_lines (
  id bigint primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  label text not null default '',
  amount numeric not null default 0,
  sort_order int not null default 0
);
create index if not exists shipping_lines_owner_idx on public.shipping_lines(owner_id);

create table if not exists public.revenue_lines (
  id bigint primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  store text not null default '',
  amount numeric not null default 0,
  sort_order int not null default 0
);
create index if not exists revenue_lines_owner_idx on public.revenue_lines(owner_id);

create table if not exists public.purchase_batches (
  id bigint primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  label text not null default '',
  purchase_ids bigint[] not null default '{}',
  revenue_ids bigint[] not null default '{}',
  sort_order int not null default 0
);
create index if not exists purchase_batches_owner_idx on public.purchase_batches(owner_id);

create table if not exists public.delivery_rows (
  id bigint primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  box_no int not null default 0,  -- 0 = unzugewiesen
  qr_data_url text,
  qr_name text,
  qr_kind text check (qr_kind in ('image', 'pdf')),
  invoice_data_url text,
  invoice_name text,
  invoice_kind text check (invoice_kind in ('image', 'pdf')),
  assigned_item_ids bigint[] not null default '{}',
  notes text not null default '',
  sort_order int not null default 0
);
create index if not exists delivery_rows_owner_idx on public.delivery_rows(owner_id);
create index if not exists delivery_rows_box_no_idx on public.delivery_rows(owner_id, box_no);

-- =========================================================
-- 6a. STORES — pro User verwaltete Verkaufs-Stores
-- =========================================================
create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null default '',
  platform text not null default '' check (platform in ('kleinanzeigen', 'ebay', 'etsy', 'discogs', 'amazon', 'shopify', 'other', '')),
  description text not null default '',
  profile_image_url text,
  emoji text not null default '',  -- optionale Fallback-Grafik
  ai_store_suggestion text,  -- welcher Store passt zu welchem Item
  affiliate_links jsonb not null default '{}',  -- {itemKeyword: affiliateUrl}
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists stores_owner_idx on public.stores(owner_id);
create unique index if not exists stores_owner_name on public.stores(owner_id, lower(name)) where name != '';

-- Item-Store Zuordnung
alter table public.purchase_items add column if not exists store_id bigint references public.stores(id) on delete set null;
alter table public.purchase_items add column if not exists list_strategy text default 'unsorted'
  check (list_strategy in ('online', 'offline', 'bundle', 'unsorted'));
alter table public.purchase_items add column if not exists affiliate_url text;
alter table public.purchase_items add column if not exists listed_at timestamptz;
alter table public.purchase_items add column if not exists recommendation text default '';
alter table public.purchase_items add column if not exists recommendation_reason text default '';
alter table public.purchase_items add column if not exists suggested_price numeric(10,2);
alter table public.purchase_items add column if not exists assigned_box_no int;

create index if not exists purchase_items_store_idx on public.purchase_items(store_id) where store_id is not null;

-- =========================================================
-- 6b. AFFILIATE LINKS — pro Item, separate Tabelle mit Multi-Links
-- =========================================================
create table if not exists public.affiliate_links (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  item_id bigint not null references public.purchase_items(id) on delete cascade,
  label text not null default '',
  url text not null default '',
  compare_price numeric(10,2),
  fetched_at timestamptz default now()
);
create index if not exists affiliate_links_item_idx on public.affiliate_links(item_id);

-- =========================================================
-- 7. ROW LEVEL SECURITY
-- =========================================================
alter table public.profiles       enable row level security;
alter table public.purchase_items  enable row level security;
alter table public.purchases     enable row level security;
alter table public.purchase_images enable row level security;
alter table public.sales         enable row level security;
alter table public.purchase_lines enable row level security;
alter table public.shipping_lines enable row level security;
alter table public.revenue_lines  enable row level security;
alter table public.purchase_batches enable row level security;
alter table public.delivery_rows  enable row level security;
alter table public.stores         enable row level security;
alter table public.affiliate_links enable row level security;

drop policy if exists "profiles_self"          on public.profiles;
drop policy if exists "purchase_items_self"   on public.purchase_items;
drop policy if exists "purchases_self"       on public.purchases;
drop policy if exists "purchase_images_self"  on public.purchase_images;
drop policy if exists "sales_self"           on public.sales;
drop policy if exists "purchase_lines_self"  on public.purchase_lines;
drop policy if exists "shipping_lines_self"  on public.shipping_lines;
drop policy if exists "revenue_lines_self"   on public.revenue_lines;
drop policy if exists "purchase_batches_self" on public.purchase_batches;
drop policy if exists "delivery_rows_self"   on public.delivery_rows;
drop policy if exists "stores_self"          on public.stores;
drop policy if exists "affiliate_links_self" on public.affiliate_links;

create policy "profiles_self"           on public.profiles           using (id = auth.uid()) with check (id = auth.uid());
create policy "purchase_items_self"    on public.purchase_items    using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "purchases_self"        on public.purchases        using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "purchase_images_self" on public.purchase_images  using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "sales_self"           on public.sales            using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "purchase_lines_self"   on public.purchase_lines   using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "shipping_lines_self"   on public.shipping_lines   using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "revenue_lines_self"   on public.revenue_lines   using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "purchase_batches_self" on public.purchase_batches using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "delivery_rows_self"   on public.delivery_rows   using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "stores_self"          on public.stores          using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "affiliate_links_self" on public.affiliate_links using (owner_id = auth.uid()) with check (owner_id = auth.uid());

-- =========================================================
-- 8. STORAGE
-- =========================================================
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;
insert into storage.buckets (id, name, public)
values ('items', 'items', true)
on conflict (id) do nothing;
insert into storage.buckets (id, name, public)
values ('purchases', 'purchases', true)
on conflict (id) do nothing;
insert into storage.buckets (id, name, public)
values ('stores', 'stores', true)
on conflict (id) do nothing;

drop policy if exists "avatar_public_read"   on storage.objects;
drop policy if exists "avatar_owner_upload" on storage.objects;
drop policy if exists "avatar_owner_update"  on storage.objects;
drop policy if exists "items_public_read"    on storage.objects;
drop policy if exists "items_owner_upload"  on storage.objects;
drop policy if exists "items_owner_delete"   on storage.objects;
drop policy if exists "purchases_public_read"  on storage.objects;
drop policy if exists "purchases_owner_upload" on storage.objects;

create policy "avatar_public_read"    on storage.objects for select using (bucket_id = 'avatars');
create policy "avatar_owner_upload"  on storage.objects for insert with check (bucket_id = 'avatars' and auth.uid() = owner);
create policy "avatar_owner_update"  on storage.objects for update using (bucket_id = 'avatars' and auth.uid() = owner);
create policy "items_public_read"    on storage.objects for select using (bucket_id = 'items');
create policy "items_owner_upload"   on storage.objects for insert with check (bucket_id = 'items' and auth.uid() = owner);
create policy "items_owner_delete"  on storage.objects for delete using (bucket_id = 'items' and auth.uid() = owner);
create policy "purchases_public_read"  on storage.objects for select using (bucket_id = 'purchases');
create policy "purchases_owner_upload" on storage.objects for insert with check (bucket_id = 'purchases' and auth.uid() = owner);

create policy "stores_public_read"  on storage.objects for select using (bucket_id = 'stores');
create policy "stores_owner_upload" on storage.objects for insert with check (bucket_id = 'stores' and auth.uid() = owner);
create policy "stores_owner_delete" on storage.objects for delete using (bucket_id = 'stores' and auth.uid() = owner);
