/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppAgentsRouteImport } from './routes/app/agents'
import { Route as AppAlertsRouteImport } from './routes/app/alerts'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppMultiposterRouteImport } from './routes/app/multiposter'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppSearchRouteImport } from './routes/app/search'
import { Route as AppMultiposterIndexRouteImport } from './routes/app/multiposter.index'
import { Route as AppMultiposterSourceRouteImport } from './routes/app/multiposter.$source'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMultiposterRoute = AppMultiposterRouteImport.update({
  id: '/multiposter',
  path: '/multiposter',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppMultiposterIndexRoute = AppMultiposterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMultiposterRoute,
} as any)
const AppMultiposterSourceRoute = AppMultiposterSourceRouteImport.update({
  id: '/$source',
  path: '/$source',
  getParentRoute: () => AppMultiposterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/agents': typeof AppAgentsRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/multiposter': typeof AppMultiposterRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/search': typeof AppSearchRoute
  '/app/multiposter/$source': typeof AppMultiposterSourceRoute
  '/app/multiposter/': typeof AppMultiposterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/agents': typeof AppAgentsRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/reports': typeof AppReportsRoute
  '/app/search': typeof AppSearchRoute
  '/app/multiposter/$source': typeof AppMultiposterSourceRoute
  '/app/multiposter': typeof AppMultiposterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/agents': typeof AppAgentsRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/multiposter': typeof AppMultiposterRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/search': typeof AppSearchRoute
  '/app/multiposter/$source': typeof AppMultiposterSourceRoute
  '/app/multiposter/': typeof AppMultiposterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/agents'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/dashboard'
    | '/app/multiposter'
    | '/app/reports'
    | '/app/search'
    | '/app/multiposter/$source'
    | '/app/multiposter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/agents'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/dashboard'
    | '/app/reports'
    | '/app/search'
    | '/app/multiposter/$source'
    | '/app/multiposter'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/agents'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/dashboard'
    | '/app/multiposter'
    | '/app/reports'
    | '/app/search'
    | '/app/multiposter/$source'
    | '/app/multiposter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/multiposter': {
      id: '/app/multiposter'
      path: '/multiposter'
      fullPath: '/app/multiposter'
      preLoaderRoute: typeof AppMultiposterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/multiposter/': {
      id: '/app/multiposter/'
      path: '/'
      fullPath: '/app/multiposter/'
      preLoaderRoute: typeof AppMultiposterIndexRouteImport
      parentRoute: typeof AppMultiposterRoute
    }
    '/app/multiposter/$source': {
      id: '/app/multiposter/$source'
      path: '/$source'
      fullPath: '/app/multiposter/$source'
      preLoaderRoute: typeof AppMultiposterSourceRouteImport
      parentRoute: typeof AppMultiposterRoute
    }
  }
}

interface AppMultiposterRouteChildren {
  AppMultiposterSourceRoute: typeof AppMultiposterSourceRoute
  AppMultiposterIndexRoute: typeof AppMultiposterIndexRoute
}

const AppMultiposterRouteChildren: AppMultiposterRouteChildren = {
  AppMultiposterSourceRoute: AppMultiposterSourceRoute,
  AppMultiposterIndexRoute: AppMultiposterIndexRoute,
}

const AppMultiposterRouteWithChildren = AppMultiposterRoute._addFileChildren(
  AppMultiposterRouteChildren,
)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMultiposterRoute: typeof AppMultiposterRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppSearchRoute: typeof AppSearchRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMultiposterRoute: AppMultiposterRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppSearchRoute: AppSearchRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
